plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'com.selectiveexporter'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'net.portswigger.burp.extensions:montoya-api:2023.11'
    implementation 'com.google.code.gson:gson:2.10.1'
}

shadowJar {
    archiveBaseName.set('SelectiveExporter')
    archiveClassifier.set('')
    archiveVersion.set('')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
